Implement a BibTeX log parser
James-Yu/LaTeX-Workshop pull request #2461
Opened 2021-01-03 20:48 UTC by jlelong

2021-01-04 21:08 UTC, jlelong commented
I would be happy to add more regex to catch bibtex warnings or errors if anyone has examples of such logs.

2021-01-05 05:27 UTC, tamuratak requested changes

2021-01-05 05:27 UTC, tamuratak commented on src/components/parser/biblogparser.ts
> +        filename = filename.replace('.aux', '.tex')
Use `/\.aux$/` to ensure it matches the extension.

2021-01-05 05:27 UTC, tamuratak commented on src/components/manager.ts
> +        /**
Remove extra spaces.

2021-01-05 05:27 UTC, tamuratak commented on src/components/parser/compilerlog.ts
> +        // this.extension = extension
You can remove the comment-outed line.

2021-01-05 07:53 UTC, jlelong commented
One more issue. When `latexmk` runs `bibtex` twice, the problems are duplicated. Need to trim logs.

2021-01-06 06:02 UTC, tamuratak approved these changes

2021-01-06 06:08 UTC, merged