Add a configurable clean command
James-Yu/LaTeX-Workshop pull request #2471
Opened 2021-01-10 06:02 UTC by jlelong

2021-01-12 05:55 UTC, tamuratak requested changes

2021-01-12 10:55 UTC, jlelong commented on src/components/cleaner.ts
> +                    reject(stderr)
You are right, there is no need to call reject here.

2021-01-12 12:19 UTC, tamuratak commented on src/components/cleaner.ts
> +                    reject(stderr)
I mean, we have to call `resolve` here.

2021-01-12 12:22 UTC, tamuratak requested changes

2021-01-12 12:22 UTC, tamuratak commented on src/components/cleaner.ts
> +                reject(err)
We should call `resolve` instead of `reject`.

2021-01-12 12:22 UTC, tamuratak commented on src/components/cleaner.ts
> +                }
We should call `resolve` here. Otherwise, the promise object will not be resolved.

2021-01-12 21:05 UTC, jlelong commented
I think the resolve vs reject issue is now fixed. We log errors occurring on `spawn` calls but yet call resolve to avoid throwing an error as we do not catch them later. 
@tamuratak thanks for your advice!

2021-01-12 23:22 UTC, tamuratak approved these changes

2021-01-13 05:28 UTC, merged

2021-01-13 06:37 UTC, jlelong commented
See the documentation: https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#cleaning-generated-files