Fix potential exponential backtracking when removing comments
James-Yu/LaTeX-Workshop pull request #2562
Opened 2021-03-05 08:41 UTC by jlelong

Related to CodeQL inefficient regular expression warning.

2021-03-05 08:50 UTC, tamuratak commented
I think the function has a bug. It does not remove a comment immediately after `\\`.

https://github.com/James-Yu/LaTeX-Workshop/blob/54fa70f22910d0fe50e991d919e4845c63694db7/src/utils/utils.ts#L29-L33

```latex
\begin{align*}
x \\%abc
y
\end{align*}
```

2021-03-05 09:02 UTC, jlelong commented
Indeed! This bug has been around for two years and nobody ever complained.

2021-03-05 09:52 UTC, jlelong commented
Not yet!

2021-03-05 12:51 UTC, tamuratak requested changes

2021-03-05 12:51 UTC, tamuratak commented on src/utils/utils.ts
> +    const pattern = '(^|[^\\\\]|(?:(?<!\\\\)\\\\\\\\))' + commentSign + '.*$'
I don't like the API. It makes things too complicated unnecessarily. Please delete the `commentSign` argument and use a literal regular expression. When we need to remove comments which begin other than `%`, let's define another function.

2021-03-06 00:32 UTC, tamuratak commented
It does not remove the following comment.

```latex
\begin{align*}
x \\\\%abc
y
\end{align*}
```

2021-03-06 05:53 UTC, jlelong commented
This was done on purpose because I thought two consecutive newlines `\\` were not valid LaTeX. Although, it is not inside `align`, it is in text mode. I will fix it.

2021-03-06 06:13 UTC, jlelong commented
It should be fine now.

2021-03-06 07:22 UTC, tamuratak approved these changes

2021-03-07 05:54 UTC, merged