Skip labels in new command definitions
James-Yu/LaTeX-Workshop pull request #2786
Opened 2021-07-01 07:21 UTC by jlelong

Close #2785

2021-07-01 13:25 UTC, jlelong commented
@tamuratak Would it make sense to add a function `isNewCommand` to `latex-utensils` ?

2021-07-01 14:06 UTC, tamuratak commented
No. We don't have to treat `newcommand` specially to parse LaTeX documents. 

To interpret LaTeX documents, we have to treat `newcommand` specially. However, interpreting LaTeX documents is out of the scope of `latex-utensils`.

2021-07-01 14:08 UTC, jlelong commented
OK, I get your point.

2021-07-02 09:09 UTC, tamuratak requested changes

2021-07-02 09:09 UTC, tamuratak commented on src/utils/utils.ts
> +import {latexParser} from 'latex-utensils'
We had  better use a type-only import:

```ts
import type {latexParser} from 'latex-utensils'
```

2021-07-02 23:41 UTC, tamuratak approved these changes

2021-07-03 16:28 UTC, merged