onEnterKey supports multi-cursors when all selected lines start with \item
James-Yu/LaTeX-Workshop pull request #3279
Opened 2022-05-03 12:11 UTC by jlelong

Fix #3278. This PR is a followup on #3255, which turned to be buggy.

Multi-cursors is only partially supported because of a limitation of vscode's API to insert a new line and indent it. So `onEnterKey` only works when all the selected lines start with `\s*\\item`. If not, we simply return a normal `Enter` keystroke.

2022-05-04 00:37 UTC, tamuratak requested changes

2022-05-04 00:37 UTC, tamuratak commented on src/commander.ts
>          void editor.edit(editBuilder => {
Instead of `void`, it would be better to return the value that `editor.edit` returns.

2022-05-04 07:51 UTC, tamuratak commented
On the following example, typing enter does nothing.

```latex
\begin{itemize}
  \item \item (Enter here)
\end{itemize}
```

2022-05-04 12:04 UTC, jlelong commented
@tamuratak Thanks a lot for catching this one!

I have refactor the three possible cases
-  Empty `\item` or `\item[]`
- `\item[blabla]`
- `\item blabla` or `\item[.*] blabla`

Considering we only enter `editor.edit` if all the selected cursors are at the end of a line starting with  `\s*\item`, the above three cases should cover all the situations. Yet, as a fallback, a newline is added with the same indentation as the current one.

2022-05-05 00:05 UTC, tamuratak approved these changes

2022-05-05 05:38 UTC, merged