Support cross-ref from `xr` package
James-Yu/LaTeX-Workshop pull request #3641
Opened 2023-01-11 03:45 UTC by James-Yu

This PR resolves #3391 by following the `\externaldocument` command provided by `xr` package.

External documents are cached in a new entry `external` in the `context` of each TeX file, and they are also watched. Upon providing references, both `includedTeX` and `external` will be iterated to create a complete list.

The optional `prefix` of `\externaldocument` is also parsed and provided in the intellisense.

A test is added to test the feature.

2023-01-15 08:12 UTC, jlelong requested changes

2023-01-16 03:03 UTC, James-Yu commented on src/components/cacher.ts
> +    // the content on disk otherwise.
I was too unfamiliar with the comment things in the past years. Will fix definitely!

2023-01-16 03:04 UTC, James-Yu commented on src/components/cacher.ts
> +                continue
Will do!

2023-01-16 03:07 UTC, James-Yu commented on src/components/cacher.ts
> +            logger.log(`External document ${externalPath} from ${filePath} .`)
Will do!

2023-01-16 03:08 UTC, James-Yu commented on src/providers/completer/reference.ts
> +                    }
I agree this is a be convoluted. I'm yet to figure a better way of implementation. Will comment carefully.

p.s. It's years of coding alone in the past, letting me forget about comment and readability. Apologize for that and will recover very fast!

2023-01-17 15:16 UTC, jlelong commented on src/providers/completer/reference.ts
> +    //  Stores the ref number.
Same as above

2023-01-17 19:25 UTC, jlelong approved these changes

2023-01-18 02:25 UTC, merged