fix #4474
James-Yu/LaTeX-Workshop pull request #4475
Opened 2024-12-02 02:37 UTC by shinyypig

By adding an extra "\n" at the end of the input text and remove it after using `tex-fmt`, the problem is solved.

![iShot_2024-12-02_10 36 07](https://github.com/user-attachments/assets/083ab30e-cc8b-4015-8bc7-2287169dec57)

2024-12-02 14:10 UTC, James-Yu requested changes
Thanks for your contribution.

2024-12-02 14:10 UTC, James-Yu commented on src/lint/latex-formatter/tex-fmt.ts
> +    process.stdin?.write(document.getText(range)+'\n')
Should add new line only if the selection is not ended by a new line char.

2024-12-02 14:10 UTC, James-Yu commented on src/lint/latex-formatter/tex-fmt.ts
> +        edits.newText = edits.newText.replace(/\n$/, '')
... and remove the new line char accordingly.

2024-12-02 14:10 UTC, James-Yu commented on src/lint/latex-formatter/tex-fmt.ts
> +    // write the document to the process, and add a newline at the end
As this is a workaround of an external piece of software, please add corresponding documents describing the date, version of tex-fmt, and the context of the workaround.

2024-12-04 02:40 UTC, shinyypig commented
I have corrected the code, but I am unsure whether it is appropriate to write the documentation directly as comments within the code.

2024-12-05 02:26 UTC, merged